pkgs:
with pkgs; [
    cool-retro-term
    androidStudioPackages.canary
    android-tools
    circup
    diylc
    gnucap
    horizon-eda
    kate
    librepcb
    logisim
    logisim-evolution
    ngspice
    pcb
    python310Packages.cirq-web
    python310Packages.cirq-rigetti
    python310Packages.cirq-pasqal
    python310Packages.cirq-ionq
    python310Packages.cirq-google
    python310Packages.cirq-core
    python310Packages.cirq-aqt
    python310Packages.cirq
    qucs
    stlink
    tkgate
    vscode # insiders?
    x11docker
    xcircuit
    xyce
    xyce-parallel
]
